# We use conda to install cromwell.

language: python

python:
  - 3.6

before_install:
  # Install conda
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

install:
  - conda install cromwell

script:
  - set -e
  - for FILE in $(find -name "*.wdl"); do echo $FILE; womtool validate $FILE; done
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git submodule foreach git checkout develop && git submodule foreach git pull; fi'
  - "git diff --exit-code || (echo ERROR: Git changes detected. Please update submodules && exit 1)"
